source 'http://rubygems.org'
gem 'sinatra', '>= 1.3.1'
gem 'sinatra-respond_to', '>= 0.8', :git => 'git://github.com/simon/sinatra-respond_to.git'
gem 'sinatra-contrib', '1.3.1'
gem 'mongo_mapper', '>= 0.9'
gem 'sinatra_more', :git => 'git@github.com:curbed/sinatra_more.git'
gem 'httparty'
gem 'json'
gem 'things-rb', :git => 'git@github.com:slowernet/things-rb.git'
gem 'activesupport'